### ISSUE TITLE
RegisterNumReads error

### ISSUE THREAD

**Issue by IvoryC** [BioLockJ-Dev-Team/sheepdog_testing_suite#135]
The RegisterNumReads module causes a MetaUtil error:

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at biolockj.util.MetaUtil.report(MetaUtil.java:548)
	at biolockj.util.MetaUtil.refreshCache(MetaUtil.java:394)
	at biolockj.util.MetaUtil.addColumn(MetaUtil.java:71)
	at biolockj.module.implicit.RegisterNumReads.runModule(RegisterNumReads.java:80)
	at biolockj.module.JavaModuleImpl.executeTask(JavaModuleImpl.java:55)
	at biolockj.Pipeline.executeModule(Pipeline.java:43)
	at biolockj.Pipeline.executeModules(Pipeline.java:191)
	at biolockj.Pipeline.runPipeline(Pipeline.java:135)
	at biolockj.BioLockJ.runPipeline(BioLockJ.java:293)
	at biolockj.BioLockJ.main(BioLockJ.java:93)

**Comment by IvoryC** [comment]
SeqFileValidator creates a similar problem.  I think its really a MetaUtil issue.

FATAL APPLICATION ERROR  -->
 Program args: -projectDir /Users/ieclabau/git/BioLockJ/pipelines -homeDir /Users/ieclabau -config metadata_filePath.properties
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at biolockj.util.MetaUtil.report(MetaUtil.java:548)
	at biolockj.util.MetaUtil.refreshCache(MetaUtil.java:394)
	at biolockj.util.MetaUtil.addColumn(MetaUtil.java:71)
	at biolockj.module.seq.SeqFileValidator.runModule(SeqFileValidator.java:116)
	at biolockj.module.JavaModuleImpl.executeTask(JavaModuleImpl.java:55)
	at biolockj.Pipeline.executeModule(Pipeline.java:43)
	at biolockj.Pipeline.executeModules(Pipeline.java:191)
	at biolockj.Pipeline.runPipeline(Pipeline.java:135)
	at biolockj.BioLockJ.runPipeline(BioLockJ.java:293)
	at biolockj.BioLockJ.main(BioLockJ.java:93)
