### ISSUE TITLE
java mis-interprets runtime parameter

### ISSUE THREAD

**Issue by IvoryC** [BioLockJ-Dev-Team/sheepdog_testing_suite#94]
$ java -jar /Users/ieclabau/git/BioLockJ/dist/BioLockJ.jar -b /Users/ieclabau/git/BioLockJ/pipelines -u /Users/ieclabau r=/Users/ieclabau/git/BioLockJ/pipelines/rarifySeqs_3_2019Sep17

Starting BioLockj...1568736772051
System encountered a FATAL ERROR
biolockj.exception.RuntimeParamException: Pipeline failed to start due to invalid runtime parameter: [ -c = /Users/ieclabau/git/BioLockJ/pipelines/rarifySeqs_3_2019Sep17/r=/Users/ieclabau/git/BioLockJ/pipelines/rarifySeqs_3_2019Sep17 ] 
System file-path not found
	at biolockj.util.RuntimeParamUtil.validateParams(RuntimeParamUtil.java:472)
	at biolockj.util.RuntimeParamUtil.registerRuntimeParameters(RuntimeParamUtil.java:294)
	at biolockj.BioLockJ.initBioLockJ(BioLockJ.java:173)
	at biolockj.BioLockJ.main(BioLockJ.java:89)
Unable to set pipeline filesystem privileges
java.lang.NullPointerException
	at biolockj.Config.pipelinePath(Config.java:390)
	at biolockj.BioLockJ.setPipelineSecurity(BioLockJ.java:300)
	at biolockj.BioLockJ.pipelineShutDown(BioLockJ.java:226)
	at biolockj.BioLockJ.main(BioLockJ.java:94)
Exception in thread "main" java.lang.NullPointerException
	at biolockj.Config.pipelinePath(Config.java:390)
	at biolockj.BioLockJ.isPipelineComplete(BioLockJ.java:68)
	at biolockj.BioLockJ.pipelineShutDown(BioLockJ.java:233)
	at biolockj.BioLockJ.main(BioLockJ.java:94)

**Comment by IvoryC** [comment]
The handling of runtime parameters was refactored.
See this pull request: https://github.com/BioLockJ-Dev-Team/BioLockJ/pull/1
Which was accepted in September 2019.
